### PR TITLE
Additional info in README and gitignore

### PR DESCRIPTION
**Pull request by Doko-Demo-Doa**
Thank you for the useful repo. And I really hope that the upstream will get merged ASAP.

This PR adds a bit more instruction lines to get it up and running. Also since it contains a lock file, `npm ci` is recommended.

### CODE REVIEW

**Comment by seproDev** [comment]
Hey, you mind reopening this upstream?
Also I would probably drop the deploy section as that will likely change.

**Comment by Doko-Demo-Doa** [comment]
Hi @seproDev , I have synced with upstream code.

**Comment by seproDev** [comment]
Oh I meant now that the `Aeg-dev/AegiSite:switch2hugo` branch has been merged in to `Aegisub/aegisite` you should reopen the PR there.

**Comment by Doko-Demo-Doa** [comment]
Thanks. I have created a new one here: [Link](https://github.com/Aegisub/aegisite/pull/19)

**Pull request closed without merging**
